### ISSUE TITLE
Application crashes on rotation change (MapView)

### ISSUE THREAD

**Issue by ismaeltoe** [umano/AndroidSlidingUpPanel#157]
I use a MapView as secondary layout in SlidingUpPanelLayout. It works at the first loading but when the user tries to rotate the device, the app crashes. I use 1 Activity with multiple fragments (Navigation Drawer implementation).

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ismaeltoe.babievents/com.ismaeltoe.babievents.MainActivity}: android.os.BadParcelableException: ClassNotFoundException when unmarshalling: com.sothree.slidinguppanel.SlidingUpPanelLayout$SavedState
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2059)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2084)
at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:3512)
at android.app.ActivityThread.access$700(ActivityThread.java:130)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1201)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:4745)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
at dalvik.system.NativeStart.main(Native Method)
Caused by: android.os.BadParcelableException: ClassNotFoundException when unmarshalling: com.sothree.slidinguppanel.SlidingUpPanelLayout$SavedState
at android.os.Parcel.readParcelable(Parcel.java:2077)
at android.os.Parcel.readValue(Parcel.java:1965)
at android.os.Parcel.readSparseArrayInternal(Parcel.java:2255)
at android.os.Parcel.readSparseArray(Parcel.java:1687)
at android.os.Parcel.readValue(Parcel.java:2022)
at android.os.Parcel.readMapInternal(Parcel.java:2226)
at android.os.Bundle.unparcel(Bundle.java:223)
at android.os.Bundle.getBundle(Bundle.java:1143)
at evm.a(SourceFile:74)
at maps.e.al.a(Unknown Source)
at maps.e.bk.a(Unknown Source)
at etx.onTransact(SourceFile:66)
at android.os.Binder.transact(Binder.java:326)
at com.google.android.gms.maps.internal.IMapViewDelegate$a$a.onCreate(Unknown Source)
at com.google.android.gms.maps.MapView$a.onCreate(Unknown Source)
at com.google.android.gms.dynamic.a$3.b(Unknown Source)
at com.google.android.gms.dynamic.a$1.a(Unknown Source)
at com.google.android.gms.maps.MapView$b.gW(Unknown Source)
at com.google.android.gms.maps.MapView$b.a(Unknown Source)
at com.google.android.gms.dynamic.a.a(Unknown Source)
at com.google.android.gms.dynamic.a.onCreate(Unknown Source)
at com.google.android.gms.maps.MapView.onCreate(Unknown Source)
at com.ismaeltoe.babievents.EventDetailsFragment.onCreateView(EventDetailsFragment.java:118)
at android.support.v4.app.Fragment.performCreateView(Fragment.java:1500)
at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:927)
at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1104)
at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1086)
at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:1884)
at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:566)
at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1163)
at android.app.Activity.performStart(Activity.java:5018)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2032)
... 12 more

**Comment by enthusiast94** [comment]
@ismaeltoe That solution worked for me as well. Thanks!

**Comment by gurappa** [comment]
@ismaeltoe / @enthusiast94 the above solution fine if map view is in activity. How would I do in case of fragment ? mapView can only be instantiated in onViewCreated() so it will be null in onCreate(). So can not do mMapView.onCreate(mapViewSavedInstanceState);. Any help ?

**Comment by enthusiast94** [comment]
@gurappa you can call mapview.onCreate() right after you have found the view within your fragment's onCreateView().
