### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by levuphuong** [umano/AndroidSlidingUpPanel#382]
Hi

I just import sample code to test.
First eclipse show error "found 2 versions of android-support-v4.jar"
Then i remove android-support-v4.jar in libs of Appcompat-v7, error was remove.
But when i launch app. it crash with logcat.
Please help me resolve this problem
Thanks

02-11 14:30:04.034: I/dalvikvm(10495): Could not find method android.support.v4.content.ContextCompat.getDrawable, referenced from method android.support.v7.internal.widget.TintManager.getDrawable
02-11 14:30:04.034: W/dalvikvm(10495): VFY: unable to resolve static method 1508: Landroid/support/v4/content/ContextCompat;.getDrawable (Landroid/content/Context;I)Landroid/graphics/drawable/Drawable;
02-11 14:30:04.034: D/dalvikvm(10495): VFY: replacing opcode 0x71 at 0x0002
02-11 14:30:04.044: D/AndroidRuntime(10495): Shutting down VM
02-11 14:30:04.044: W/dalvikvm(10495): threadid=1: thread exiting with uncaught exception (group=0x41d338b0)
02-11 14:30:04.054: E/AndroidRuntime(10495): FATAL EXCEPTION: main
02-11 14:30:04.054: E/AndroidRuntime(10495): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.sothree.slidinguppanel.demo/com.sothree.slidinguppanel.demo.DemoActivity}: android.view.InflateException: Binary XML file line #24: Error inflating class android.support.v7.widget.Toolbar
02-11 14:30:04.054: E/AndroidRuntime(10495): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2266)
02-11 14:30:04.054: E/AndroidRuntime(10495): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2316)
02-11 14:30:04.054: E/AndroidRuntime(10495): 	at android.app.ActivityThread.access$600(ActivityThread.java:150)
02-11 14:30:04.054: E/AndroidRuntime(10495): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1298)
02-11 14:30:04.054: E/AndroidRuntime(10495): 	at android.os.Handler.dispatchMessage(Handler.java:99)
02-11 14:30:04.054: E/AndroidRuntime(10495): 	at android.os.Looper.loop(Looper.java:213)
02-11 14:30:04.054: E/AndroidRuntime(10495): 	at android.app.ActivityThread.main(ActivityThread.java:5225)
02-11 14:30:04.054: E/AndroidRuntime(10495): 	at java.lang.reflect.Method.invokeNative(Native Method)
02-11 14:30:04.054: E/AndroidRuntime(10495): 	at java.lang.reflect.Method.invoke(Method.java:525)
02-11 14:30:04.054: E/AndroidRuntime(10495): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:741)
02-11 14:30:04.054: E/AndroidRuntime(10495): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:557)
02-11 14:30:04.054: E/AndroidRuntime(10495): 	at dalvik.system.NativeStart.main(Native Method)
02-11 14:30:04.054: E/AndroidRuntime(10495): Caused by: android.view.InflateException: Binary XML file line #24: Error inflating class android.support.v7.widget.Toolbar
02-11 14:30:04.054: E/AndroidRuntime(10495): 	at android.view.LayoutInflater.createView(LayoutInflater.java:620)
02-11 14:30:04.054: E/AndroidRuntime(10495): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696)
02-11 14:30:04.054: E/AndroidRuntime(10495): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
02-11 14:30:04.054: E/AndroidRuntime(10495): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
02-11 14:30:04.054: E/AndroidRuntime(10495): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
02-11 14:30:04.054: E/AndroidRuntime(10495): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
02-11 14:30:04.054: E/AndroidRuntime(10495): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
02-11 14:30:04.054: E/AndroidRuntime(10495): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
02-11 14:30:04.054: E/AndroidRuntime(10495): 	at android.support.v7.app.ActionBarActivityDelegateBase.setContentView(ActionBarActivityDelegateBase.java:228)
02-11 14:30:04.054: E/AndroidRuntime(10495): 	at android.support.v7.app.ActionBarActivity.setContentView(ActionBarActivity.java:102)
02-11 14:30:04.054: E/AndroidRuntime(10495): 	at com.sothree.slidinguppanel.demo.DemoActivity.onCreate(DemoActivity.java:30)
02-11 14:30:04.054: E/AndroidRuntime(10495): 	at android.app.Activity.performCreate(Activity.java:5133)
02-11 14:30:04.054: E/AndroidRuntime(10495): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
02-11 14:30:04.054: E/AndroidRuntime(10495): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2230)
02-11 14:30:04.054: E/AndroidRuntime(10495): 	... 11 more
02-11 14:30:04.054: E/AndroidRuntime(10495): Caused by: java.lang.reflect.InvocationTargetException
02-11 14:30:04.054: E/AndroidRuntime(10495): 	at java.lang.reflect.Constructor.constructNative(Native Method)
02-11 14:30:04.054: E/AndroidRuntime(10495): 	at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
02-11 14:30:04.054: E/AndroidRuntime(10495): 	at android.view.LayoutInflater.createView(LayoutInflater.java:594)
02-11 14:30:04.054: E/AndroidRuntime(10495): 	... 24 more
02-11 14:30:04.054: E/AndroidRuntime(10495): Caused by: java.lang.NoSuchMethodError: android.support.v4.content.ContextCompat.getDrawable
02-11 14:30:04.054: E/AndroidRuntime(10495): 	at android.support.v7.internal.widget.TintManager.getDrawable(TintManager.java:133)
02-11 14:30:04.054: E/AndroidRuntime(10495): 	at android.support.v7.internal.widget.TintTypedArray.getDrawable(TintTypedArray.java:62)
02-11 14:30:04.054: E/AndroidRuntime(10495): 	at android.support.v7.widget.Toolbar.<init>(Toolbar.java:249)
02-11 14:30:04.054: E/AndroidRuntime(10495): 	at android.support.v7.widget.Toolbar.<init>(Toolbar.java:191)
02-11 14:30:04.054: E/AndroidRuntime(10495): 	... 27 more

**Comment by levuphuong** [comment]
This problem was resolved by rmove android-v4.jar in library and import appcompat-v7 to library
regard,
