### ISSUE TITLE
compile issue

### ISSUE THREAD

**Issue by jjhesk** [umano/AndroidSlidingUpPanel#406]
```

Error:Execution failed for task ':driver_app:dexDebug'.
> com.android.ide.common.internal.LoggedErrorException: Failed to run command:
	M:\tempAndroid\sdk\build-tools\21.1.2\dx.bat --dex --no-optimize --output F:\backupgithub\TaxiOneCall\TaxiCallAndroid\driver_app\build\intermediates\dex\debug --input-list=F:\backupgithub\TaxiOneCall\TaxiCallAndroid\driver_app\build\intermediates\tmp\dex\debug\inputList.txt
Error Code:
	2
Output:
	UNEXPECTED TOP-LEVEL EXCEPTION:
	com.android.dex.DexException: Multiple dex files define Lcom/nineoldandroids/animation/Animator$AnimatorListener;
		at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
		at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
		at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
		at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
		at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
		at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:454)
		at com.android.dx.command.dexer.Main.runMonoDex(Main.java:303)
		at com.android.dx.command.dexer.Main.run(Main.java:246)
		at com.android.dx.command.dexer.Main.main(Main.java:215)
		at com.android.dx.command.Main.main(Main.java:106)

```
looks like there is a compiling issue.

**Comment by KlassenKonstantin** [comment]
It seams like you already import a different version of nineoldandroid  in your project. Either remove your dependency or exclude nineoldandroid from this project or make sure that you use the same version.

**Comment by jjhesk** [comment]
I tried and another exception occurred.

**Comment by tokudu** [comment]
@jjhesk please post the error that you are facing now

**Comment by tokudu** [comment]
reopen if still having issues.
