### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by kssaboo** [umano/AndroidSlidingUpPanel#431]
java.lang.ArrayIndexOutOfBoundsException: length=2; index=2
       at com.sothree.slidinguppanel.ViewDragHelper.saveLastMotion(ViewDragHelper.java:847)
       at com.sothree.slidinguppanel.ViewDragHelper.shouldInterceptTouchEvent(ViewDragHelper.java:1029)
       at com.sothree.slidinguppanel.SlidingUpPanelLayout.onInterceptTouchEvent(SlidingUpPanelLayout.java:844)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2052)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2420)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2153)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2420)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2153)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2420)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2153)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2420)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2153)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2252)
       at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1587)
       at android.app.Activity.dispatchTouchEvent(Activity.java:2507)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2200)
       at android.view.View.dispatchPointerEvent(View.java:8320)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4558)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4430)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3988)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4042)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4011)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4122)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4019)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4179)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3988)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4042)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4011)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4019)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3988)
       at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6333)
       at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6249)
       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6220)
       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6185)
       at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6413)
       at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
       at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(InputEventReceiver.java)
       at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:176)
       at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:6386)
       at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:6432)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:803)
       at android.view.Choreographer.doCallbacks(Choreographer.java:603)
       at android.view.Choreographer.doFrame(Choreographer.java:571)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:789)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:157)
       at android.app.ActivityThread.main(ActivityThread.java:5335)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
       at dalvik.system.NativeStart.main(NativeStart.java)

android 4.4.2, SM-N900S

**Comment by tokudu** [comment]
Can you provide some repro steps?

**Comment by kssaboo** [comment]
Don't know. I got this from crash report.
