### ISSUE TITLE
At Android 4.3 R$styleable is not found exception

### ISSUE THREAD

**Issue by qkboo** [umano/AndroidSlidingUpPanel#527]
I have been tested Galaxy Nexus, Emulator by 4.4 kakat, running on these device are always error.

>      Caused by: java.lang.NoClassDefFoundError: com.sothree.slidinguppanel.library.R$styleable
            at com.sothree.slidinguppanel.SlidingUpPanelLayout.<init>(SlidingUpPanelLayout.java:294)
            at com.sothree.slidinguppanel.SlidingUpPanelLayout.<init>(SlidingUpPanelLayout.java:272)

I have been used below complex Layout, but on above 4.4, running ok.

```
<android.support.v4.widget.DrawerLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/drawer_layout"
    android:paddingLeft="@dimen/activity_horizontal_margin"
    android:paddingRight="@dimen/activity_horizontal_margin"
    android:paddingTop="@dimen/activity_vertical_margin"
    android:paddingBottom="@dimen/activity_vertical_margin"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context=".MainActivity">

    <RelativeLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent">


        <com.sothree.slidinguppanel.SlidingUpPanelLayout
            android:id="@+id/sliding_layout"
            android:layout_above="@+id/menu_layout"
            android:gravity="top"
            android:layout_width="match_parent"
            android:layout_height="match_parent" >


            <!-- MAIN CONTENT -->
            <FrameLayout
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:clickable="true"
                android:focusable="false"
                android:focusableInTouchMode="true" >


                <WebView
                    android:id="@+id/webView_mfg"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"/>


                <ScrollView
                    android:id="@+id/scrollView_login"
                    android:layout_width="match_parent"
                    android:layout_height="match_parent"
                    android:clickable="true"
                    android:focusable="false"
                    android:focusableInTouchMode="true"
                    android:visibility="gone" >

                    <LinearLayout
                        android:id="@+id/layout_login"
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content"
                        android:layout_gravity="center_vertical|center_horizontal"
                        android:background="#2d2f31"
                        android:clickable="true"
                        android:focusable="false"
                        android:focusableInTouchMode="true"
                        android:gravity="center_vertical|left"
                        android:orientation="vertical">

                        <ImageView
                            android:id="@+id/image_login_title"
                            android:layout_width="wrap_content"
                            android:layout_height="wrap_content"
                            android:src="@drawable/login_title" />

                        <EditText
                            android:id="@+id/edit_id"
                            android:layout_width="match_parent"
                            android:layout_height="wrap_content"
                            android:background="@drawable/id_edit_bg" >

                            <requestFocus />
                        </EditText>

                        <EditText
                            android:id="@+id/edit_pw"
                            android:layout_width="match_parent"
                            android:layout_height="wrap_content"
                            android:background="@drawable/pw_edit_bg"
                            android:inputType="textPassword" />


                        <CheckBox
                            android:id="@+id/check_remem_id"
                            android:layout_width="match_parent"
                            android:layout_height="wrap_content"
                            android:layout_gravity="center_vertical|center_horizontal"
                            android:button="@drawable/remem_id_cb"
                            android:checked="false"
                            android:gravity="left"
                            android:visibility="visible" />

                        <ImageView
                            android:id="@+id/image_login"
                            android:layout_width="match_parent"
                            android:layout_height="wrap_content"
                            android:background="@drawable/login_login_btn" />

                        <ImageView
                            android:id="@+id/image_member_join"
                            android:layout_width="wrap_content"
                            android:layout_height="wrap_content"
                            android:src="@drawable/member_join_text" />

                        <LinearLayout
                            android:layout_width="wrap_content"
                            android:layout_height="wrap_content"
                            >
                            <ImageView
                                android:id="@+id/image_id_find"
                                android:layout_width="wrap_content"
                                android:layout_height="wrap_content"
                                android:src="@drawable/id_find_text" />
                            <ImageView
                                android:id="@+id/image_pwd_find"
                                android:layout_width="wrap_content"
                                android:layout_height="wrap_content"
                                android:src="@drawable/pwd_find_text" />
                        </LinearLayout>


                        <LinearLayout
                            android:layout_width="match_parent"
                            android:layout_height="wrap_content"
                            android:background="#2a2a2b"
                            android:orientation="horizontal" >

                            <ImageView
                                android:id="@+id/image_facebook"
                                android:layout_width="0dp"
                                android:layout_weight="1"
                                android:layout_height="wrap_content"
                                android:background="@drawable/facebook_btn" />

                            <com.kakao.widget.LoginButton
                                android:id="@+id/com_kakao_login"
                                android:layout_width="0dp"
                                android:layout_weight="1"
                                android:layout_height="wrap_content"/>

                        </LinearLayout>
                    </LinearLayout>
                </ScrollView>
            </FrameLayout>

            <!-- SLIDING LAYOUT -->


            <LinearLayout
                android:id="@+id/dragView"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:orientation="vertical"
                android:clickable="true"
                android:focusable="false"
                android:background="#00000000">

                <LinearLayout
                    android:id="@+id/layout_drag_top"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:orientation="horizontal"
                    android:gravity="center_vertical|right"
                    android:background="@drawable/card_slide_top">

                    <ImageView
                        android:id="@+id/image_top_arrow"
                        android:layout_width="wrap_content"
                        android:layout_height="wrap_content"
                        android:layout_gravity="center_vertical|right"
                        android:src="@drawable/card_top_open_btn" >
                    </ImageView>

                </LinearLayout>

                <LinearLayout
                    android:layout_width="match_parent"
                    android:layout_height="0dp"
                    android:layout_weight="1"
                    android:orientation="horizontal"
                    android:gravity="center_vertical|center_horizontal"
                    android:background="@drawable/card_slide_bg">

                    <LinearLayout
                        android:id="@+id/layout_card"
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content"
                        android:orientation="horizontal"
                        android:layout_gravity="center_vertical|center_horizontal"
                        android:gravity="center_vertical|center_horizontal"
                        android:visibility="visible" >

                        <ImageView
                            android:id="@+id/imageView1"
                            android:layout_width="0dp"
                            android:layout_height="wrap_content"
                            android:layout_weight="1"
                            android:src="@drawable/card" />

                        <RelativeLayout
                            android:layout_width="0dp"
                            android:layout_height="wrap_content"
                            android:layout_weight="1"
                            android:gravity="center_vertical|center_horizontal"
                            android:orientation="vertical" >

                            <ImageView
                                android:id="@+id/image_card_bg"
                                android:layout_width="wrap_content"
                                android:layout_height="wrap_content"
                                android:layout_centerHorizontal="true"
                                android:layout_centerInParent="false"
                                android:src="@drawable/card_bg"
                                android:visibility="visible" />

                            <ImageView
                                android:id="@+id/image_bottom_login"
                                android:layout_width="match_parent"
                                android:layout_height="wrap_content"
                                android:layout_alignParentBottom="false"
                                android:layout_alignParentTop="true"
                                android:layout_alignTop="@id/image_card_bg"
                                android:layout_centerHorizontal="true"
                                android:background="@drawable/login_btn" />

                            <ImageView
                                android:id="@+id/image_bottom_join"
                                android:layout_width="match_parent"
                                android:layout_height="wrap_content"
                                android:layout_alignBottom="@id/image_card_bg"
                                android:layout_alignParentBottom="false"
                                android:layout_centerHorizontal="false"
                                android:layout_centerInParent="true"
                                android:background="@drawable/join_btn" />

                        </RelativeLayout>

                    </LinearLayout>

                    <LinearLayout
                        android:id="@+id/layout_barcode"
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content"
                        android:orientation="horizontal"
                        android:layout_gravity="center_vertical|center_horizontal"
                        android:gravity="center_vertical|center_horizontal"
                        android:visibility="gone">

                        <RelativeLayout
                            android:layout_width="0dp"
                            android:layout_height="wrap_content"
                            android:layout_weight="1"
                            android:gravity="center_vertical|center_horizontal"
                            android:layout_gravity="center_vertical|center_horizontal"
                            android:orientation="vertical" >

                            <ImageView
                                android:id="@+id/image_card_bg1"
                                android:layout_width="wrap_content"
                                android:layout_height="wrap_content"
                                android:layout_centerHorizontal="true"
                                android:src="@drawable/card_bg"/>

                            <LinearLayout
                                android:layout_width="wrap_content"
                                android:layout_height="wrap_content"
                                android:layout_centerInParent="true"
                                android:orientation="vertical" >

                                <ImageView
                                    android:id="@+id/image_barcode"
                                    android:layout_width="wrap_content"
                                    android:layout_height="wrap_content"
                                    android:scaleType="centerInside"
                                    android:src="@drawable/member_barcode" />

                                <TextView
                                    android:layout_width="wrap_content"
                                    android:layout_height="wrap_content"
                                    android:id="@+id/text_member_no"
                                    android:layout_below="@id/image_barcode"
                                    android:text="회원번호 : 00001234" />
                            </LinearLayout>


                        </RelativeLayout>

                        <LinearLayout
                            android:layout_width="0dp"
                            android:layout_height="wrap_content"
                            android:layout_weight="1"
                            android:gravity="center_vertical|left"
                            android:layout_gravity="center_vertical|center_horizontal"
                            android:orientation="vertical" >

                            <LinearLayout
                                android:layout_width="wrap_content"
                                android:layout_height="wrap_content">

                                <ImageView
                                    android:id="@+id/image_visit"
                                    android:layout_width="wrap_content"
                                    android:layout_height="wrap_content"
                                    android:background="@drawable/visit" />

                                <TextView
                                    android:layout_width="wrap_content"
                                    android:layout_height="wrap_content"
                                    android:id="@+id/text_visit"
                                    android:text="방문횟수 : 0" />

                            </LinearLayout>

                            <LinearLayout
                                android:layout_width="wrap_content"
                                android:layout_height="wrap_content"
                                >

                                <ImageView
                                    android:id="@+id/image_buy"
                                    android:layout_width="wrap_content"
                                    android:layout_height="wrap_content"
                                    android:background="@drawable/buy"/>

                                <TextView
                                    android:layout_width="wrap_content"
                                    android:layout_height="wrap_content"
                                    android:id="@+id/text_buy"
                                    android:text="구매금액 : 0원" />

                            </LinearLayout>

                            <LinearLayout
                                android:layout_width="wrap_content"
                                android:layout_height="wrap_content">

                                <ImageView
                                    android:id="@+id/image_coupon"
                                    android:layout_width="wrap_content"
                                    android:layout_height="wrap_content"
                                    android:background="@drawable/coupon" />

                                <TextView
                                    android:layout_width="wrap_content"
                                    android:layout_height="wrap_content"
                                    android:id="@+id/text_coupon"
                                    android:text="보유쿠폰 : 0개" />

                            </LinearLayout>

                        </LinearLayout>

                    </LinearLayout>

                </LinearLayout>

            </LinearLayout>
        </com.sothree.slidinguppanel.SlidingUpPanelLayout>


        <LinearLayout
            android:id="@+id/menu_layout"
            android:layout_width="fill_parent"
            android:layout_height="wrap_content"
            android:layout_alignParentBottom="true"
            android:gravity="center"
            android:orientation="horizontal" >

            <ImageView
                android:id="@+id/home_btn"
                android:layout_width="0dp"
                android:layout_height="wrap_content"
                android:layout_weight="1"
                android:src="@drawable/abc_ratingbar_full_material" />

            <ImageView
                android:id="@+id/membership_btn"
                android:layout_width="0dp"
                android:layout_height="wrap_content"
                android:layout_weight="1"
                android:src="@drawable/abc_ratingbar_full_material" />

            <ImageView
                android:id="@+id/menu_btn"
                android:layout_width="0dp"
                android:layout_height="wrap_content"
                android:layout_weight="1"
                android:src="@drawable/abc_ratingbar_full_material" />
            <ImageView
                android:id="@+id/store_btn"
                android:layout_width="0dp"
                android:layout_height="wrap_content"
                android:layout_weight="1"
                android:src="@drawable/abc_ratingbar_full_material" />
            <ImageView
                android:id="@+id/event_btn"
                android:layout_width="0dp"
                android:layout_height="wrap_content"
                android:layout_weight="1"
                android:src="@drawable/abc_ratingbar_full_material" />

        </LinearLayout>
    </RelativeLayout>

</android.support.v4.widget.DrawerLayout>

```

**Comment by tokudu** [comment]
Can you provide a sample project where this happens?

**Comment by tokudu** [comment]
Closing due to inactivity
