### ISSUE TITLE
ClassNotFoundException with v3.0.0

### ISSUE THREAD

**Issue by dgabor19** [umano/AndroidSlidingUpPanel#554]
Hi,

Can you help us to find out what may have caused this exception what the fix is for it? It seems it came from this lib.
We experienced this crash when the app was in the background and opened it.

10-13 19:58:46.024    5189-5189/? E/Parcel﹕ Class not found when unmarshalling: com.sothree.slidinguppanel.SlidingUpPanelLayout$SavedState
    java.lang.ClassNotFoundException: com.sothree.slidinguppanel.SlidingUpPanelLayout$SavedState
            at java.lang.Class.classForName(Native Method)
            at java.lang.Class.forName(Class.java:308)
            at android.os.Parcel.readParcelableCreator(Parcel.java:2275)
            at android.os.Parcel.readParcelable(Parcel.java:2239)
            at android.os.Parcel.readValue(Parcel.java:2146)
            at android.os.Parcel.readSparseArrayInternal(Parcel.java:2540)
            at android.os.Parcel.readSparseArray(Parcel.java:1868)
            at android.os.Parcel.readValue(Parcel.java:2203)
            at android.os.Parcel.readArrayMapInternal(Parcel.java:2479)
            at android.os.BaseBundle.unparcel(BaseBundle.java:221)
            at android.os.Bundle.getBundle(Bundle.java:782)
            at com.google.android.gms.maps.internal.cq.a(SourceFile:74)
            at com.google.maps.api.android.lib6.d.et.a(Unknown Source)
            at com.google.maps.api.android.lib6.d.ae.a(Unknown Source)
            at com.google.android.gms.maps.internal.w.onTransact(SourceFile:66)
            at android.os.Binder.transact(Binder.java:395)
            at com.google.android.gms.maps.internal.IMapViewDelegate$zza$zza.onCreate(Unknown Source)
            at com.google.android.gms.maps.MapView$zza.onCreate(Unknown Source)
            at com.google.android.gms.dynamic.zza$3.zzb(Unknown Source)
            at com.google.android.gms.dynamic.zza$1.zza(Unknown Source)
            at com.google.android.gms.maps.MapView$zzb.zzxL(Unknown Source)
            at com.google.android.gms.maps.MapView$zzb.zza(Unknown Source)
            at com.google.android.gms.dynamic.zza.zza(Unknown Source)
            at com.google.android.gms.dynamic.zza.onCreate(Unknown Source)
            at com.google.android.gms.maps.MapView.onCreate(Unknown Source)
            at com.pfoinc.shield.fragments.MainFragment.onViewCreated(MainFragment.java:157)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1045)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1207)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1189)
            at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:2001)
            at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:165)
            at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:507)
            at com.pfoinc.shield.BaseActivity.onStart(BaseActivity.java:92)
            at com.pfoinc.shield.MainActivity.onStart(MainActivity.java:345)
            at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1234)
            at android.app.Activity.performStart(Activity.java:6258)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2621)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2723)
            at android.app.ActivityThread.access$900(ActivityThread.java:172)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1422)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:145)
            at android.app.ActivityThread.main(ActivityThread.java:5832)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.sothree.slidinguppanel.SlidingUpPanelLayout$SavedState" on path: DexPathList[[zip file "/data/data/com.google.android.gms/app_chimera/chimera-module-root/module-588df5a5ceb113dbbd16a6b4eefe2d0baa24f6a7/MapsModule.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
            at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
            at java.lang.Class.classForName(Native Method)
            at java.lang.Class.forName(Class.java:308)
            at android.os.Parcel.readParcelableCreator(Parcel.java:2275)
            at android.os.Parcel.readParcelable(Parcel.java:2239)
            at android.os.Parcel.readValue(Parcel.java:2146)
            at android.os.Parcel.readSparseArrayInternal(Parcel.java:2540)
            at android.os.Parcel.readSparseArray(Parcel.java:1868)
            at android.os.Parcel.readValue(Parcel.java:2203)
            at android.os.Parcel.readArrayMapInternal(Parcel.java:2479)
            at android.os.BaseBundle.unparcel(BaseBundle.java:221)
            at android.os.Bundle.getBundle(Bundle.java:782)
            at com.google.android.gms.maps.internal.cq.a(SourceFile:74)
            at com.google.maps.api.android.lib6.d.et.a(Unknown Source)
            at com.google.maps.api.android.lib6.d.ae.a(Unknown Source)
            at com.google.android.gms.maps.internal.w.onTransact(SourceFile:66)
            at android.os.Binder.transact(Binder.java:395)
            at com.google.android.gms.maps.internal.IMapViewDelegate$zza$zza.onCreate(Unknown Source)
            at com.google.android.gms.maps.MapView$zza.onCreate(Unknown Source)
            at com.google.android.gms.dynamic.zza$3.zzb(Unknown Source)
            at com.google.android.gms.dynamic.zza$1.zza(Unknown Source)
            at com.google.android.gms.maps.MapView$zzb.zzxL(Unknown Source)
            at com.google.android.gms.maps.MapView$zzb.zza(Unknown Source)
            at com.google.android.gms.dynamic.zza.zza(Unknown Source)
            at com.google.android.gms.dynamic.zza.onCreate(Unknown Source)
            at com.google.android.gms.maps.MapView.onCreate(Unknown Source)
            at com.pfoinc.shield.fragments.MainFragment.onViewCreated(MainFragment.java:157)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1045)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1207)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1189)
            at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:2001)
            at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:165)
            at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:507)
            at com.pfoinc.shield.BaseActivity.onStart(BaseActivity.java:92)
            at com.pfoinc.shield.MainActivity.onStart(MainActivity.java:345)
            at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1234)
            at android.app.Activity.performStart(Activity.java:6258)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2621)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2723)
            at android.app.ActivityThread.access$900(ActivityThread.java:172)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1422)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:145)
            at android.app.ActivityThread.main(ActivityThread.java:5832)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
    Suppressed: java.lang.ClassNotFoundException: com.sothree.slidinguppanel.SlidingUpPanelLayout$SavedState
            at java.lang.Class.classForName(Native Method)
            at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
            at java.lang.BootClassLo
10-13 19:58:46.024    5189-5189/? D/AndroidRuntime﹕ Shutting down VM
10-13 19:58:46.024    5189-5189/? E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.pfoinc.shield, PID: 5189
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.pfoinc.shield/com.pfoinc.shield.MainActivity}: android.os.BadParcelableException: ClassNotFoundException when unmarshalling: com.sothree.slidinguppanel.SlidingUpPanelLayout$SavedState
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2658)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2723)
            at android.app.ActivityThread.access$900(ActivityThread.java:172)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1422)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:145)
            at android.app.ActivityThread.main(ActivityThread.java:5832)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
     Caused by: android.os.BadParcelableException: ClassNotFoundException when unmarshalling: com.sothree.slidinguppanel.SlidingUpPanelLayout$SavedState
            at android.os.Parcel.readParcelableCreator(Parcel.java:2289)
            at android.os.Parcel.readParcelable(Parcel.java:2239)
            at android.os.Parcel.readValue(Parcel.java:2146)
            at android.os.Parcel.readSparseArrayInternal(Parcel.java:2540)
            at android.os.Parcel.readSparseArray(Parcel.java:1868)
            at android.os.Parcel.readValue(Parcel.java:2203)
            at android.os.Parcel.readArrayMapInternal(Parcel.java:2479)
            at android.os.BaseBundle.unparcel(BaseBundle.java:221)
            at android.os.Bundle.getBundle(Bundle.java:782)
            at com.google.android.gms.maps.internal.cq.a(SourceFile:74)
            at com.google.maps.api.android.lib6.d.et.a(Unknown Source)
            at com.google.maps.api.android.lib6.d.ae.a(Unknown Source)
            at com.google.android.gms.maps.internal.w.onTransact(SourceFile:66)
            at android.os.Binder.transact(Binder.java:395)
            at com.google.android.gms.maps.internal.IMapViewDelegate$zza$zza.onCreate(Unknown Source)
            at com.google.android.gms.maps.MapView$zza.onCreate(Unknown Source)
            at com.google.android.gms.dynamic.zza$3.zzb(Unknown Source)
            at com.google.android.gms.dynamic.zza$1.zza(Unknown Source)
            at com.google.android.gms.maps.MapView$zzb.zzxL(Unknown Source)
            at com.google.android.gms.maps.MapView$zzb.zza(Unknown Source)
            at com.google.android.gms.dynamic.zza.zza(Unknown Source)
            at com.google.android.gms.dynamic.zza.onCreate(Unknown Source)
            at com.google.android.gms.maps.MapView.onCreate(Unknown Source)
            at com.pfoinc.shield.fragments.MainFragment.onViewCreated(MainFragment.java:157)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1045)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1207)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1189)
            at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:2001)
            at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:165)
            at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:507)
            at com.pfoinc.shield.BaseActivity.onStart(BaseActivity.java:92)
            at com.pfoinc.shield.MainActivity.onStart(MainActivity.java:345)
            at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1234)
            at android.app.Activity.performStart(Activity.java:6258)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2621)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2723)
            at android.app.ActivityThread.access$900(ActivityThread.java:172)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1422)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:145)
            at android.app.ActivityThread.main(ActivityThread.java:5832)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)

**Comment by tokudu** [comment]
Can you provide some repro steps? I can't seem to repro.

**Comment by maverick-2013** [comment]
try to select "Do not keep activities" in developer options, crash appears when going back to activity.
