### ISSUE TITLE
IndexOutOfBoundsException: Invalid index 0, size is 0

### ISSUE THREAD

**Issue by githubdoramon** [umano/AndroidSlidingUpPanel#590]
I'm getting this error, both on Android 4 and 5

Fatal Exception: java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
       at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:251)
       at java.util.ArrayList.get(ArrayList.java:304)
       at android.support.v4.view.ViewPager.performDrag(SourceFile:2162)
       at android.support.v4.view.ViewPager.onTouchEvent(SourceFile:2081)
       at android.view.View.dispatchTouchEvent(View.java:7348)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2235)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1932)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2241)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1946)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2241)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1946)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2241)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1946)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2241)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1946)
       at com.sothree.slidinguppanel.SlidingUpPanelLayout.dispatchTouchEvent(SourceFile:962)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2241)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1946)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2241)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1946)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2241)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1946)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2241)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1946)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2241)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1946)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2241)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1946)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2241)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1946)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2241)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1946)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2241)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1946)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2241)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1946)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2241)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1946)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2241)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1946)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2241)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1946)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:1974)
       at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1426)
       at android.app.Activity.dispatchTouchEvent(Activity.java:2446)
       at android.support.v7.internal.view.WindowCallbackWrapper.dispatchTouchEvent(SourceFile:60)
       at android.support.v7.internal.view.WindowCallbackWrapper.dispatchTouchEvent(SourceFile:60)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:1922)
       at android.view.View.dispatchPointerEvent(View.java:7528)
       at android.view.ViewRootImpl.deliverPointerEvent(ViewRootImpl.java:3626)
       at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:3554)
       at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:4818)
       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:4778)
       at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:4930)
       at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:179)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:125)
       at android.os.Looper.loop(Looper.java:140)
       at android.app.ActivityThread.main(ActivityThread.java:5299)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
       at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by tokudu** [comment]
What version of the library are you using? I thought I fixed a similar issue already.

**Comment by githubdoramon** [comment]
The last one (3.2)... Im algo getting a lot of errors on a other view on
the onTouchEvent, probably a reflection from this one.

**Comment by githubdoramon** [comment]
@tokudu no news on this issue?

**Comment by kwmt** [comment]
@tokudu Thank you for replying. Oh, really? I'm using version 3.1.1. I'm going to try to update the latest version.

**Comment by githubdoramon** [comment]
anyone?? guess I'll have to dowload the library and try to fix myself :(

**Comment by tokudu** [comment]
Looking at your stack trace, the crash is happening inside of your ViewPager. This doesn't look related to the library.

**Comment by githubdoramon** [comment]
@tokudu haven't you seen this line on the stack?

at com.sothree.slidinguppanel.SlidingUpPanelLayout.dispatchTouchEvent(SourceFile:962)

It happens BECAUSE of the sliding panel... I have a view pager in the Sliding Panel

**Comment by gurappa** [comment]
@githubdoramon could you fix it ? I am facing the similar issue.
@tokudu any fixes gone in for this issue ?

**Comment by githubdoramon** [comment]
@gurappa not yet... I'm starting to think I'll have to build something from scratch :( ... 10% of the users are getting this error... And I can't even simulate it.

**Comment by tokudu** [comment]
@githubdoramon @gurappa I can't reproduce this - and we haven't seen this issue in our app, if you can provide me with a sample project and / or repro steps I can debug. Otherwise, I'm unfortunately powerless here.

I'll reopen the issue for now.

**Comment by githubdoramon** [comment]
@tokudu the problem is I can't reproduce either... I have the sliding panel, and a view pager on top of it.... I try everything to get the crash, but I keep only getting user having the crash

**Comment by githubdoramon** [comment]
@tokudu please close this issue... the real problem is with my view pager, not the sliding panel! Im really sorry!

**Comment by gurappa** [comment]
Hi @githubdoramon may I know what was the issue ? I will see if it is the same issue with our code too. Thanks in advance.

**Comment by githubdoramon** [comment]
@gurappa I'm not yet 100% sure it solved... but I didn't got new exceptions on the last version I released... I extended the view pager, and made it possible to disable the swyping when changing its contents. Also made a check for childs... here is the code

public class OnOffViewPager extends ViewPager {

    public boolean enabled = true;

    public OnOffViewPager(Context context) {
        super(context);
    }

    public OnOffViewPager(Context context, AttributeSet attrs) {
        super(context, attrs);
    }

    @Override
    public boolean onTouchEvent(MotionEvent ev) {
        if(this.enabled) {
            if (getCurrentItem() == 0 && getChildCount() == 0) {
                return false;
            }
            return super.onTouchEvent(ev);
        } else {
            return false;
        }
    }

    @Override
    public boolean onInterceptTouchEvent(MotionEvent ev) {
        if(this.enabled) {
            if (getCurrentItem() == 0 && getChildCount() == 0) {
                return false;
            }
            return super.onInterceptTouchEvent(ev);
        } else {
            return false;
        }
    }
}

**Comment by gurappa** [comment]
Thanks for the info @githubdoramon :-)

**Comment by smallmouse2009** [comment]
cause reason: this issue is caused by the source file. In ViewPager setAdaper() mItems will set null.When you darg viewpager and when the setAdapter is called then this issue occured.you can see the performDrag method mItems.get(0) don't add size check.

**Comment by smallmouse2009** [comment]
cause reason: this issue is caused by the source file. In ViewPager setAdaper() mItems will set null.When you darg viewpager and when the setAdapter is called then this issue occured.you can see the performDrag method mItems.get(0) don't add size check.
solve : using notifyDataChanged to refresh data instead of setAdapter.

if(mCarinfoAdapter == null){
      mCarinfoAdapter = new CarInfoViewPagerAdapter(views);
}else{
      mCarinfoAdapter.setViews(views);
}
if(vp_carinfo.getAdapter() == null){
      vp_carinfo.setAdapter(mCarinfoAdapter);
}else {
      mCarinfoAdapter.notifyDataSetChanged();
}

thanks.
