### ISSUE TITLE
Bug: importing the project shows error while importing

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [umano/AndroidSlidingUpPanel#621]
This:

Error:No such property: nexusUsername for class: org.gradle.api.publication.maven.internal.ant.DefaultGroovyMavenDeployer

What should I do?

**Comment by AndroidDeveloperLB** [comment]
OK, I've fixed it by removing the file "maven_push.gradle" and removing this line from the library's gradle file :

    apply from: '../maven_push.gradle'


But now I get this error at runtime :


java.lang.RuntimeException: Unable to start activity ComponentInfo{com.sothree.slidinguppanel.demo/com.sothree.slidinguppanel.demo.DemoActivity}: java.lang.IllegalArgumentException: AppCompat does not support the current theme features: { windowActionBar: false, windowActionBarOverlay: false, android:windowIsFloating: false, windowActionModeOverlay: false, windowNoTitle: false }
                                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2184)
                                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2233)
                                                                                   at android.app.ActivityThread.access$800(ActivityThread.java:135)
                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                   at android.os.Looper.loop(Looper.java:136)
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5001)
                                                                                   at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                   at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
                                                                                   at dalvik.system.NativeStart.main(Native Method)
                                                                                Caused by: java.lang.IllegalArgumentException: AppCompat does not support the current theme features: { windowActionBar: false, windowActionBarOverlay: false, android:windowIsFloating: false, windowActionModeOverlay: false, windowNoTitle: false }
                                                                                   at android.support.v7.app.AppCompatDelegateImplV7.createSubDecor(AppCompatDelegateImplV7.java:422)
                                                                                   at android.support.v7.app.AppCompatDelegateImplV7.ensureSubDecor(AppCompatDelegateImplV7.java:279)
                                                                                   at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:253)
                                                                                   at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:109)
                                                                                   at com.sothree.slidinguppanel.demo.DemoActivity.onCreate(DemoActivity.java:37)
                                                                                   at android.app.Activity.performCreate(Activity.java:5231)
                                                                                   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
                                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2148)
                                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2233) 
                                                                                   at android.app.ActivityThread.access$800(ActivityThread.java:135) 
                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196) 
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                   at android.os.Looper.loop(Looper.java:136) 
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5001) 
                                                                                   at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                                   at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785) 
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601) 
                                                                                   at dalvik.system.NativeStart.main(Native Method)

**Comment by tokudu** [comment]
Fixed in master.

**Comment by AndroidDeveloperLB** [comment]
@tokudu Still cannot import well.
Why was it closed?
