### ISSUE TITLE
Crash when change panel state

### ISSUE THREAD

**Issue by AlexTip** [umano/AndroidSlidingUpPanel#625]
Sometime my app crashed hwen I change panel state
Log:
java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
                                                     at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
                                                     at java.util.ArrayList.get(ArrayList.java:308)
                                                     at android.widget.HeaderViewListAdapter.isEnabled(HeaderViewListAdapter.java:164)
                                                     at android.widget.ListView.dispatchDraw(ListView.java:3327)
                                                     at android.view.View.draw(View.java:16181)
                                                     at android.widget.AbsListView.draw(AbsListView.java:4142)
                                                     at android.view.View.updateDisplayListIfDirty(View.java:15174)
                                                     at android.view.View.draw(View.java:15948)
                                                     at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                                                     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                                                     at android.view.View.updateDisplayListIfDirty(View.java:15169)
                                                     at android.view.View.draw(View.java:15948)
                                                     at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                                                     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                                                     at android.view.View.updateDisplayListIfDirty(View.java:15169)
                                                     at android.view.View.draw(View.java:15948)
                                                     at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                                                     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                                                     at android.view.View.draw(View.java:16181)
                                                     at android.view.View.updateDisplayListIfDirty(View.java:15174)
                                                     at android.view.View.draw(View.java:15948)
                                                     at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                                                     at com.sothree.slidinguppanel.SlidingUpPanelLayout.drawChild(SlidingUpPanelLayout.java:1214)
                                                     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                                                     at android.view.View.draw(View.java:16181)
                                                     at com.sothree.slidinguppanel.SlidingUpPanelLayout.draw(SlidingUpPanelLayout.java:1257)
                                                     at android.view.View.updateDisplayListIfDirty(View.java:15174)
                                                     at android.view.View.draw(View.java:15948)
                                                     at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                                                     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                                                     at android.view.View.updateDisplayListIfDirty(View.java:15169)
                                                     at android.view.View.draw(View.java:15948)
                                                     at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                                                     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                                                     at android.view.View.draw(View.java:16181)
                                                     at android.view.View.updateDisplayListIfDirty(View.java:15174)
                                                     at android.view.View.draw(View.java:15948)
                                                     at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                                                     at android.support.v4.widget.DrawerLayout.drawChild(DrawerLayout.java:1229)
                                                     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                                                     at android.view.View.updateDisplayListIfDirty(View.java:15169)
                                                     at android.view.View.draw(View.java:15948)
                                                     at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                                                     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                                                     at android.view.View.updateDisplayListIfDirty(View.java:15169)
                                                     at android.view.View.draw(View.java:15948)
                                                     at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                                                     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                                                     at android.view.View.updateDisplayListIfDirty(View.java:15169)
                                                     at android.view.View.draw(View.java:15948)
                                                     at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                                                     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                                                     at android.view.View.updateDisplayListIfDirty(View.java:15169)
                                                     at android.view.View.draw(View.java:15948)
                                                     at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                                                     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                                                     at android.view.View.updateDisplayListIfDirty(View.java:15169)
                                                     at android.view.View.draw(View.java:15948)
                                                     at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                                                     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                                                     at android.view.View.draw(View.java:16181)
                                                     at com.android.internal.policy.PhoneWindow$DecorView.draw(PhoneWindow.java:2690)
                                                     at android.view.View.updateDisplayListIfDirty(View.java:15174)
                                                     at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:281)
                                                     at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:287)
                                                     at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:322)
                                                 	at android.view.ViewRoo

**Comment by tokudu** [comment]
This issue is not related to the library. The crash is happening inside of HeaderViewListAdapter that you are using.
