### ISSUE TITLE
Binary XML file line #8: Error inflating class com.sothree.slidinguppanel.SlidingUpPanelLayout

### ISSUE THREAD

**Issue by areatecnica2015** [umano/AndroidSlidingUpPanel#705]
Hi, I have a problem while using this library on a 10" Samsung Tablet, with a custom Cyanogen Rom.
On others devices it works well.

E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.app.lus, PID: 6876
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.app.lus/com.app.lus.MainActivity}: android.view.InflateException: Binary XML file line #8: Error inflating class com.sothree.slidinguppanel.SlidingUpPanelLayout
   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2214)
   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2263)
   at android.app.ActivityThread.access$800(ActivityThread.java:146)
   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1207)
   at android.os.Handler.dispatchMessage(Handler.java:102)
   at android.os.Looper.loop(Looper.java:136)
   at android.app.ActivityThread.main(ActivityThread.java:5145)
   at java.lang.reflect.Method.invokeNative(Native Method)
   at java.lang.reflect.Method.invoke(Method.java:515)
   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:795)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:611)
   at dalvik.system.NativeStart.main(Native Method)
Caused by: android.view.InflateException: Binary XML file line #8: Error inflating class com.sothree.slidinguppanel.SlidingUpPanelLayout
   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:707)
   at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
   at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
   at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
   at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
   at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:267)
   at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:129)
   at com.app.lus.MainActivity.onCreate(MainActivity.java:23)
   at android.app.Activity.performCreate(Activity.java:5231)
   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2168)
   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2263) 
   at android.app.ActivityThread.access$800(ActivityThread.java:146) 
   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1207) 
   at android.os.Handler.dispatchMessage(Handler.java:102) 
   at android.os.Looper.loop(Looper.java:136) 
   at android.app.ActivityThread.main(ActivityThread.java:5145) 
   at java.lang.reflect.Method.invokeNative(Native Method) 
   at java.lang.reflect.Method.invoke(Method.java:515) 
   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:795) 
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:611) 
   at dalvik.system.NativeStart.main(Native Method) 
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.sothree.slidinguppanel.SlidingUpPanelLayout" on path: DexPathList[[zip file "/data/app/com.app.lus-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.app.lus-1, /vendor/lib, /system/lib]]
   at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
   at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
   at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
   at android.view.LayoutInflater.createView(LayoutInflater.java:559)
   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696)
   at android.view.LayoutInflater.rInflate(LayoutInflater.java:755) 
   at android.view.LayoutInflater.inflate(LayoutInflater.java:492) 
   at android.view.LayoutInflater.inflate(LayoutInflater.java:397) 
   at android.view.LayoutInflater.inflate(LayoutInflater.java:353) 
   at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:267) 
   at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:129) 
   at com.app.lus.MainActivity.onCreate(MainActivity.java:23) 
   at android.app.Activity.performCreate(Activity.java:5231) 
   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087) 
   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2168) 
   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2263) 
   at android.app.ActivityThread.access$800(ActivityThread.java:146) 
   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1207) 
   at android.os.Handler.dispatchMessage(Handler.java:102) 
   at android.os.Looper.loop(Looper.java:136) 
   at android.app.ActivityThread.main(ActivityThread.java:5145) 
   at java.lang.reflect.Method.invokeNative(Native Method) 
   at java.lang.reflect.Method.invoke(Method.java:515) 
   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:795) 
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:611) 
   at dalvik.system.NativeStart.main(Native Method)

**Comment by shineon84** [comment]
Hi, i have this problem too, but only on devices with android version <  4.0.3. I've tried in android 2.3 and the problem appears! Did you solve it? Thank you!

**Comment by syeddanishali8080** [comment]
The same is occurring in my case. I'm running it on 5.0.

**Comment by MiguelCatalan** [comment]
+1

**Comment by MiguelCatalan** [comment]
This is my layout, in case it is usefull:

`<android.support.v4.widget.DrawerLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:id="@+id/drawer_layout"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    
    <FrameLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <com.sothree.slidinguppanel.SlidingUpPanelLayout
            android:id="@+id/sliding_layout"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:gravity="bottom"
            app:umanoDragView="@+id/dragView"
            app:umanoOverlay="false"
            app:umanoPanelHeight="68dp"
            app:umanoShadowHeight="0dp">

            <include layout="@layout/view_2" />

            <include layout="@layout/view_1" />

        </com.sothree.slidinguppanel.SlidingUpPanelLayout>

        <android.support.design.widget.FloatingActionButton />
    </FrameLayout>


    
    <include layout="@layout/something" />

</android.support.v4.widget.DrawerLayout>`

**Comment by Dechcaudron** [comment]
+1

**Comment by Dechcaudron** [comment]
I just managed to fix this problem. Why it only happens mainly on Samsung devices, I don't know.

The root of the problem is the use of MultiDex. I won't lie, I don't know much about build processes in Java, but today I found out that to minify the size of the output, MultiDex will remove classes and methods from the build if they are not explicitly mentioned in any .java source file. Thus, unless you mention SlidingUpPanelLayout as say, a var type in any of your app's java source files (xml resources don't count),  MultiDex will consider they are not used and thus, they can be safely removed from the build output.

The solution to this: I haven't really put enough time into it to finally know if MultiDex can be configured with a configuration file, but you'll probably be better off not using it and resorting to [ProGuard](https://developer.android.com/studio/build/shrink-code.html). I won't get into details here, but it allows you do decide which code to remove and which to keep, as well as to ofuscate the resulting bytecode of the app. That will solve the problem.

In any case, *this is not a library issue* and thus, this issue thread should be now closed by the admins.

Cheers everybody!

**Comment by RohitK1992** [comment]
Any solution for the above issue ?

**Comment by minorsecond** [comment]
@Dechcaudron I've got `multiDexEnabled false` in my gradle file, and I'm running an AOSP ROM on a Samsung device and I still get the error. Did you do something different?

**Comment by Dechcaudron** [comment]
@minorsecond sadly I don't actively develop for Android anymore, but if I recall correctly I didn't just disable multiDex. Don't ask me how, but using proguard fixed it at the time for us. Sorry I can't help you better :/
