### ISSUE TITLE
SlidingUpPanelLayout.java line 1172 com.sothree.slidinguppanel.SlidingUpPanelLayout.drawChild

### ISSUE THREAD

**Issue by jinmiao** [umano/AndroidSlidingUpPanel#743]
Fatal Exception: java.lang.StackOverflowError
       at android.graphics.Paint.getTextRunAdvances(Paint.java:1711)
       at android.text.TextLine.handleText(TextLine.java:749)
       at android.text.TextLine.handleRun(TextLine.java:972)
       at android.text.TextLine.measureRun(TextLine.java:416)
       at android.text.TextLine.measure(TextLine.java:295)
       at android.text.TextLine.metrics(TextLine.java:269)
       at android.text.Layout.getLineExtent(Layout.java:1322)
       at android.text.Layout.getLineWidth(Layout.java:1288)
       at android.widget.TextView.getRightFadingEdgeStrength(TextView.java:9326)
       at android.view.View.draw(View.java:11101)
       at android.view.View.getDisplayList(View.java:10444)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3167)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2793)
       at android.view.View.getDisplayList(View.java:10442)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3167)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2793)
       at android.view.View.getDisplayList(View.java:10442)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3167)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2793)
       at android.view.View.getDisplayList(View.java:10442)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3167)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2793)
       at android.view.View.draw(View.java:11017)
       at android.widget.FrameLayout.draw(FrameLayout.java:450)
       at android.view.View.getDisplayList(View.java:10444)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3167)
       at android.support.v7.widget.RecyclerView.drawChild(RecyclerView.java:4134)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2793)
       at android.view.View.draw(View.java:11017)
       at android.support.v7.widget.RecyclerView.draw(RecyclerView.java:3543)
       at android.view.View.getDisplayList(View.java:10444)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3167)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2793)
       at android.view.View.draw(View.java:11017)
       at android.view.View.getDisplayList(View.java:10444)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3167)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2793)
       at android.view.View.draw(View.java:11017)
       at android.widget.FrameLayout.draw(FrameLayout.java:450)
       at android.view.View.getDisplayList(View.java:10444)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3167)
       at android.support.v7.widget.RecyclerView.drawChild(RecyclerView.java:4134)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2793)
       at android.view.View.draw(View.java:11017)
       at android.support.v7.widget.RecyclerView.draw(RecyclerView.java:3543)
       at android.view.View.getDisplayList(View.java:10444)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3167)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2793)
       at android.view.View.getDisplayList(View.java:10442)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3167)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2793)
       at android.view.View.draw(View.java:11017)
       at android.support.v4.view.ViewPager.draw(ViewPager.java:2405)
       at android.view.View.getDisplayList(View.java:10444)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3167)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2793)
       at android.view.View.getDisplayList(View.java:10442)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3167)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2793)
       at android.view.View.getDisplayList(View.java:10442)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3167)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2793)
       at android.view.View.getDisplayList(View.java:10442)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3167)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2793)
       at android.view.View.getDisplayList(View.java:10442)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3167)
       at android.support.design.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1132)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2793)
       at android.view.View.getDisplayList(View.java:10442)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3167)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2793)
       at android.view.View.getDisplayList(View.java:10442)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3167)
       at android.support.v4.widget.DrawerLayout.drawChild(DrawerLayout.java:1377)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2793)
       at android.view.View.getDisplayList(View.java:10442)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3167)
       at com.sothree.slidinguppanel.SlidingUpPanelLayout.drawChild(SlidingUpPanelLayout.java:1172)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2793)
       at android.view.View.draw(View.java:11017)
       at com.sothree.slidinguppanel.SlidingUpPanelLayout.draw(SlidingUpPanelLayout.java:1225)
       at android.view.View.getDisplayList(View.java:10444)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3167)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2793)
       at android.view.View.getDisplayList(View.java:10442)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3167)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2793)
       at android.view.View.getDisplayList(View.java:10442)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3167)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2793)
       at android.view.View.getDisplayList(View.java:10442)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3167)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2793)
       at android.view.View.getDisplayList(View.java:10442)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3167)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2793)
       at android.view.View.draw(View.java:11017)
       at android.widget.FrameLayout.draw(FrameLayout.java:450)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2212)
       at android.view.View.getDisplayList(View.java:10444)
       at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:903)
       at android.view.ViewRootImpl.draw(ViewRootImpl.java:2123)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1810)
       at android.view.ViewRootImpl.handleMessage(ViewRootImpl.java:2700)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:156)
       at android.app.ActivityThread.main(ActivityThread.java:5109)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:991)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:758)
       at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by mariosp87** [comment]
Hello there,

i am getting the same error as above. 
I am using the below version:
compile 'com.sothree.slidinguppanel:library:3.1.1'

Following is the Stuck Trace:

com.sothree.slidinguppanel.SlidingUpPanelLayout.drawChild
SlidingUpPanelLayout.java - line 1190
java.lang.StackOverflowError
android.text.TextLine.handleRun TextLine.java:898
android.text.TextLine.measureRun TextLine.java:414
android.text.TextLine.measure TextLine.java:293
android.text.TextLine.metrics TextLine.java:267
android.text.Layout.getLineExtent Layout.java:998
android.text.Layout.drawText Layout.java:329
android.text.Layout.draw Layout.java:205
android.text.BoringLayout.draw BoringLayout.java:400
android.widget.TextView.onDraw TextView.java:5271
android.view.View.draw View.java:14740
android.view.View.getDisplayList View.java:13636
android.view.View.getDisplayList View.java:13678
android.view.View.draw View.java:14457
android.view.ViewGroup.drawChild ViewGroup.java:3117
android.view.ViewGroup.dispatchDraw ViewGroup.java:2954
android.view.View.draw View.java:14743
android.view.View.getDisplayList View.java:13636
android.view.View.getDisplayList View.java:13678
android.view.View.draw View.java:14457
android.view.ViewGroup.drawChild ViewGroup.java:3117
android.view.ViewGroup.dispatchDraw ViewGroup.java:2954
android.view.View.draw View.java:14743
android.view.View.getDisplayList View.java:13636
android.view.View.getDisplayList View.java:13678
android.view.View.draw View.java:14457
android.view.ViewGroup.drawChild ViewGroup.java:3117
android.view.ViewGroup.dispatchDraw ViewGroup.java:2954
android.view.View.draw View.java:14743
android.view.View.getDisplayList View.java:13636
android.view.View.getDisplayList View.java:13678
android.view.View.draw View.java:14457
android.view.ViewGroup.drawChild ViewGroup.java:3117
android.view.ViewGroup.dispatchDraw ViewGroup.java:2954
android.view.View.draw View.java:14743
android.view.View.getDisplayList View.java:13636
android.view.View.getDisplayList View.java:13678
android.view.View.draw View.java:14457
android.view.ViewGroup.drawChild ViewGroup.java:3117
android.view.ViewGroup.dispatchDraw ViewGroup.java:2954
android.view.View.draw View.java:14743
android.view.View.getDisplayList View.java:13636
android.view.View.getDisplayList View.java:13678
android.view.View.draw View.java:14457
android.view.ViewGroup.drawChild ViewGroup.java:3117
android.view.ViewGroup.dispatchDraw ViewGroup.java:2954
android.view.View.draw View.java:14743
android.view.View.getDisplayList View.java:13636
android.view.View.getDisplayList View.java:13678
android.view.View.draw View.java:14457
android.view.ViewGroup.drawChild ViewGroup.java:3117
android.support.v7.widget.RecyclerView.drawChild RecyclerView.java:4477
android.view.ViewGroup.dispatchDraw ViewGroup.java:2954
android.view.View.draw View.java:14743
android.support.v7.widget.RecyclerView.draw RecyclerView.java:3869
android.view.View.getDisplayList View.java:13636
android.view.View.getDisplayList View.java:13678
android.view.View.draw View.java:14457
android.view.ViewGroup.drawChild ViewGroup.java:3117
android.view.ViewGroup.dispatchDraw ViewGroup.java:2954
android.view.View.draw View.java:14743
android.view.View.getDisplayList View.java:13636
android.view.View.getDisplayList View.java:13678
android.view.View.draw View.java:14457
android.view.ViewGroup.drawChild ViewGroup.java:3117
android.view.ViewGroup.dispatchDraw ViewGroup.java:2961
android.view.View.draw View.java:14743
android.view.View.getDisplayList View.java:13636
android.view.View.getDisplayList View.java:13678
android.view.View.draw View.java:14457
android.view.ViewGroup.drawChild ViewGroup.java:3117
android.view.ViewGroup.dispatchDraw ViewGroup.java:2954
android.view.View.getDisplayList View.java:13631
android.view.View.getDisplayList View.java:13678
android.view.View.draw View.java:14457
android.view.ViewGroup.drawChild ViewGroup.java:3117
android.view.ViewGroup.dispatchDraw ViewGroup.java:2954
android.view.View.draw View.java:14743
android.support.v4.view.ViewPager.draw ViewPager.java:2443
android.view.View.getDisplayList View.java:13636
android.view.View.getDisplayList View.java:13678
android.view.View.draw View.java:14457
android.view.ViewGroup.drawChild ViewGroup.java:3117
android.view.ViewGroup.dispatchDraw ViewGroup.java:2954
android.view.View.getDisplayList View.java:13631
android.view.View.getDisplayList View.java:13678
android.view.View.draw View.java:14457
android.view.ViewGroup.drawChild ViewGroup.java:3117
android.view.ViewGroup.dispatchDraw ViewGroup.java:2954
android.view.View.draw View.java:14743
android.view.View.getDisplayList View.java:13636
android.view.View.getDisplayList View.java:13678
android.view.View.draw View.java:14457
android.view.ViewGroup.drawChild ViewGroup.java:3117
android.view.ViewGroup.dispatchDraw ViewGroup.java:2954
android.view.View.getDisplayList View.java:13631
android.view.View.getDisplayList View.java:13678
android.view.View.draw View.java:14457
android.view.ViewGroup.drawChild ViewGroup.java:3117
android.view.ViewGroup.dispatchDraw ViewGroup.java:2954
android.view.View.draw View.java:14743
android.view.View.getDisplayList View.java:13636
android.view.View.getDisplayList View.java:13678
android.view.View.draw View.java:14457
android.view.ViewGroup.drawChild ViewGroup.java:3117
android.support.design.widget.CoordinatorLayout.drawChild CoordinatorLayout.java:1230
android.view.ViewGroup.dispatchDraw ViewGroup.java:2954
android.view.View.getDisplayList View.java:13631
android.view.View.getDisplayList View.java:13678
android.view.View.draw View.java:14457
android.view.ViewGroup.drawChild ViewGroup.java:3117
android.view.ViewGroup.dispatchDraw ViewGroup.java:2954
android.view.View.getDisplayList View.java:13631
android.view.View.getDisplayList View.java:13678
android.view.View.draw View.java:14457
android.view.ViewGroup.drawChild ViewGroup.java:3117
com.sothree.slidinguppanel.SlidingUpPanelLayout.drawChild SlidingUpPanelLayout.java:1190
android.view.ViewGroup.dispatchDraw ViewGroup.java:2954
android.view.View.draw View.java:14743
com.sothree.slidinguppanel.SlidingUpPanelLayout.draw SlidingUpPanelLayout.java:1243
android.view.View.getDisplayList View.java:13636
android.view.View.getDisplayList View.java:13678
android.view.View.draw View.java:14457
android.view.ViewGroup.drawChild ViewGroup.java:3117
android.view.ViewGroup.dispatchDraw ViewGroup.java:2954
android.view.View.getDisplayList View.java:13631
android.view.View.getDisplayList View.java:13678
android.view.View.draw View.java:14457
android.view.ViewGroup.drawChild ViewGroup.java:3117
android.support.v4.widget.DrawerLayout.drawChild DrawerLayout.java:1379
android.view.ViewGroup.dispatchDraw ViewGroup.java:2954
android.view.View.getDisplayList View.java:13631
android.view.View.getDisplayList View.java:13678
android.view.View.draw View.java:14457
android.view.ViewGroup.drawChild ViewGroup.java:3117
android.view.ViewGroup.dispatchDraw ViewGroup.java:2954
android.view.View.getDisplayList View.java:13631
android.view.View.getDisplayList View.java:13678
android.view.View.draw View.java:14457
android.view.ViewGroup.drawChild ViewGroup.java:3117
android.view.ViewGroup.dispatchDraw ViewGroup.java:2954
android.view.View.draw View.java:14743
android.widget.FrameLayout.draw FrameLayout.java:472
android.view.View.getDisplayList View.java:13636
android.view.View.getDisplayList View.java:13678
android.view.View.draw View.java:14457
android.view.ViewGroup.drawChild ViewGroup.java:3117
android.view.ViewGroup.dispatchDraw ViewGroup.java:2954
android.view.View.getDisplayList View.java:13631
android.view.View.getDisplayList View.java:13678
android.view.View.draw View.java:14457
android.view.ViewGroup.drawChild ViewGroup.java:3117
android.view.ViewGroup.dispatchDraw ViewGroup.java:2954
android.view.View.getDisplayList View.java:13631
android.view.View.getDisplayList View.java:13678
android.view.View.draw View.java:14457
android.view.ViewGroup.drawChild ViewGroup.java:3117
android.view.ViewGroup.dispatchDraw ViewGroup.java:2954
android.view.View.getDisplayList View.java:13631
android.view.View.getDisplayList View.java:13678
android.view.View.draw View.java:14457
android.view.ViewGroup.drawChild ViewGroup.java:3117
android.view.ViewGroup.dispatchDraw ViewGroup.java:2954
android.view.View.draw View.java:14743
android.widget.FrameLayout.draw FrameLayout.java:472
com.android.internal.policy.impl.PhoneWindow$DecorView.draw PhoneWindow.java:2329
android.view.View.getDisplayList View.java:13636
android.view.View.getDisplayList View.java:13678
android.view.HardwareRenderer$GlRenderer.buildDisplayList HardwareRenderer.java:1570
android.view.HardwareRenderer$GlRenderer.draw HardwareRenderer.java:1449
android.view.ViewRootImpl.draw ViewRootImpl.java:2401
android.view.ViewRootImpl.performDraw ViewRootImpl.java:2273
android.view.ViewRootImpl.performTraversals ViewRootImpl.java:1903
android.view.ViewRootImpl.doTraversal ViewRootImpl.java:1020
android.view.ViewRootImpl$TraversalRunnable.run ViewRootImpl.java:5762
android.view.Choreographer$CallbackRecord.run Choreographer.java:771
android.view.Choreographer.doCallbacks Choreographer.java:574
android.view.Choreographer.doFrame Choreographer.java:544
android.view.Choreographer$FrameDisplayEventReceiver.run Choreographer.java:757
android.os.Handler.handleCallback Handler.java:733
android.os.Handler.dispatchMessage Handler.java:95
android.os.Looper.loop Looper.java:149
android.app.ActivityThread.main ActivityThread.java:5257
java.lang.reflect.Method.invokeNative Method.java
java.lang.reflect.Method.invoke Method.java:515
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run ZygoteInit.java:793
com.android.internal.os.ZygoteInit.main ZygoteInit.java:609
dalvik.system.NativeStart.main NativeStart.java

Thanks.

**Comment by mariosp87** [comment]
Hello again,

is the above crash already fixed in a newer version? I have version 3.1.1
From my crash report this crash was mainly on Android 4.4.2.

Any answer will be appreciated.
Thanks a lot.

**Comment by binhbinhquyen** [comment]
binhquyenb@gmail.com
