### ISSUE TITLE
java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid item position 0(offset:0).state:5

### ISSUE THREAD

**Issue by Millerscript** [umano/AndroidSlidingUpPanel#824]
I have a project with Google Map and use PlaceAutoComplete, while I write directions, from time to time this gives me the following error:

"Java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid item position 0 (offset: 0) .state: 5"

Full Error Code:

  java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid item position 0(offset:0).state:5
                                                                                 at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4957)
                                                                                 at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4913)
                                                                                 at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2029)
                                                                                 at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1414)
                                                                                 at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1377)
                                                                                 at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:578)
                                                                                 at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3260)
                                                                                 at android.support.v7.widget.RecyclerView.onMeasure(RecyclerView.java:2788)
                                                                                 at android.view.View.measure(View.java:18804)
                                                                                 at android.widget.RelativeLayout.measureChild(RelativeLayout.java:676)
                                                                                 at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:479)
                                                                                 at android.view.View.measure(View.java:18804)
                                                                                 at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1626)
                                                                                 at android.view.View.measure(View.java:18804)
                                                                                 at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:715)
                                                                                 at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
                                                                                 at android.view.View.measure(View.java:18804)
                                                                                 at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5954)
                                                                                 at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                                 at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:135)
                                                                                 at android.view.View.measure(View.java:18804)
                                                                                 at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5954)
                                                                                 at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
                                                                                 at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
                                                                                 at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
                                                                                 at android.view.View.measure(View.java:18804)
                                                                                 at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5954)
                                                                                 at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                                 at android.view.View.measure(View.java:18804)
                                                                                 at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5954)
                                                                                 at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
                                                                                 at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
                                                                                 at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
                                                                                 at android.view.View.measure(View.java:18804)
                                                                                 at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5954)
                                                                                 at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                                 at com.android.internal.policy.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2643)
                                                                                 at android.view.View.measure(View.java:18804)
                                                                                 at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2112)
                                                                                 at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1228)
                                                                                 at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1464)
                                                                                 at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1119)
                                                                                 at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6060)
                                                                                 at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
                                                                                 at android.view.Choreographer.doCallbacks(Choreographer.java:670)
                                                                                 at android.view.Choreographer.doFrame(Choreographer.java:606)
                                                                                 at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
                                                                                 at android.os.Handler.handleCallback(Handler.java:746)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                 at android.os.Looper.loop(Looper.java:148)
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5443)
                                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
                                                       
ADAPTER CODE:

public class PlacesAutoCompleteAdapter extends RecyclerView.Adapter<PlacesAutoCompleteAdapter.PredictionHolder> implements Filterable {

    private ArrayList<PlaceAutocomplete> mResultList;
    private GoogleApiClient mGoogleApiClient;
    private LatLngBounds mBounds;
    private AutocompleteFilter mPlaceFilter;

    private Context mContext;
    private int layout;

    public PlacesAutoCompleteAdapter(Context context, int resource, GoogleApiClient googleApiClient,
                                     LatLngBounds bounds, AutocompleteFilter filter) {
        mContext = context;
        layout = resource;
        mGoogleApiClient = googleApiClient;
        mBounds = bounds;
        mPlaceFilter = filter;
        //mPlaceFilter = new AutocompleteFilter.Builder().setTypeFilter(AutocompleteFilter.TYPE_FILTER_ADDRESS).build();
        //AutocompleteFilter mFilter = new AutocompleteFilter.Builder().setTypeFilter(AutocompleteFilter.TYPE_FILTER_ADDRESS).build();
    }

    public void setBounds(LatLngBounds bounds) {
        mBounds = bounds;
    }

    @Override
    public Filter getFilter() {
        Filter filter = new Filter() {
            @Override
            protected FilterResults performFiltering(CharSequence constraint) {
                FilterResults results = new FilterResults();
                if (constraint != null) {

                    mResultList = getAutocomplete(constraint);

                    if (mResultList != null) {
                        results.values = mResultList;
                        results.count = mResultList.size();
                    }
                }
                return results;
            }

            @Override
            protected void publishResults(CharSequence constraint, FilterResults results) {
                if (results != null && results.count > 0) {
                    notifyDataSetChanged();
                }else{
                    notifyDataSetChanged();
                }
            }
        };
        return filter;
    }

    private ArrayList<PlaceAutocomplete> getAutocomplete(CharSequence constraint) {

        if (mGoogleApiClient.isConnected()) {

            PendingResult<AutocompletePredictionBuffer> results = Places
                    .GeoDataApi
                    .getAutocompletePredictions(mGoogleApiClient, constraint.toString(), null, mPlaceFilter); //mBounds, mPlaceFilter

            Log.e("", "Text entry: " + constraint.toString());

            AutocompletePredictionBuffer autocompletePredictions = results.await(60, TimeUnit.SECONDS);

            final Status status = autocompletePredictions.getStatus();

            if (!status.isSuccess()) {

                /*Toast.makeText(mContext, "Error contacting API: " + status.toString(), Toast.LENGTH_SHORT).show();*/

                Log.e("", "Error getting autocomplete prediction API call: " + status.toString());

                autocompletePredictions.release();
                return null;
            }

            Log.i("", "Query completed. Received test " + autocompletePredictions.getCount() + " predictions.");

            Iterator<AutocompletePrediction> iterator = autocompletePredictions.iterator();

            ArrayList resultList = new ArrayList<>(autocompletePredictions.getCount());

            while (iterator.hasNext()) {

                AutocompletePrediction prediction = iterator.next();
                // Get the details of this prediction and copy it into a new PlaceAutocomplete object.
                resultList.add(new PlaceAutocomplete(prediction.getPlaceId(), prediction.getFullText(null)));

                Log.i("","");

                //notifyDataSetChanged();
            }

            autocompletePredictions.release();

            return resultList;
        }
        return null;
    }

    @Override
    public PredictionHolder onCreateViewHolder(ViewGroup viewGroup, int i) {
        LayoutInflater layoutInflater = (LayoutInflater) mContext.getSystemService(Context.LAYOUT_INFLATER_SERVICE);
        View convertView = layoutInflater.inflate(layout, viewGroup, false);
        PredictionHolder mPredictionHolder = new PredictionHolder(convertView);
        return mPredictionHolder;
    }

    @Override
    public void onBindViewHolder(PredictionHolder mPredictionHolder, final int i) {

        try{
            if(mResultList.get(i) != null){
                Log.e("Typing direction", "...:: "+i);
                mPredictionHolder.mPrediction.setText(mResultList.get(i).description);

            }else{
                Log.e("Position crashed", "..::ii::.. "+i);
            }
        }catch (Exception e){
            Log.e("position 1(offset:1)",e.getMessage().toString());
        }
        /*
            if(mResultList.get(i).description != null){
                Log.e("Typing direction", "..."+i);
                mPredictionHolder.mPrediction.setText(mResultList.get(i).description);

            }
        * */
    }

    @Override
    public int getItemCount() {
        if(mResultList != null)
            return mResultList.size();
        else
            return 0;
    }

    public PlaceAutocomplete getItem(int position) {
        if (mResultList!=null && mResultList.size()>0)
            return mResultList.get(position);
        return null;
    }

    public class PredictionHolder extends RecyclerView.ViewHolder {
        private TextView mPrediction;
        private RelativeLayout mRow;
        public PredictionHolder(View itemView) {

            super(itemView);
            mPrediction = (TextView) itemView.findViewById(R.id.address);
            mRow=(RelativeLayout)itemView.findViewById(R.id.predictedRow);
        }

    }

    public class PlaceAutocomplete {
        public CharSequence placeId;
        public CharSequence description;

        PlaceAutocomplete(CharSequence placeId, CharSequence description) {
            this.placeId = placeId;
            this.description = description;
        }

        @Override
        public String toString() {
            return description.toString();
        }
    }
}

CODE IN FRAGMENT:

        mAutoCompleteAdapter =  new PlacesAutoCompleteAdapter(getActivity(),
                R.layout.adapter_search_view,
                googleMapsApiDirector.getGoogleApiClient(), null, null);

        mRecyclerView=(RecyclerView)view.findViewById(R.id.recyclerView);

        mLinearLayoutManager=new LinearLayoutManager(getActivity());

        //mRecyclerView.getRecycledViewPool().clear();
        //mAutoCompleteAdapter.notifyDataSetChanged();

        mRecyclerView.setLayoutManager(mLinearLayoutManager);
        mRecyclerView.setAdapter(mAutoCompleteAdapter);

        mRecyclerView.addOnItemTouchListener(
            new RecyclerItemClickListener(getActivity(), new RecyclerItemClickListener.OnItemClickListener() {
                @Override
                public void onItemClick(View view, int position) {
                    final PlacesAutoCompleteAdapter.PlaceAutocomplete item = mAutoCompleteAdapter.getItem(position);
                    if (item!=null) {
                        final String placeId = String.valueOf(item.placeId);
                        PendingResult<PlaceBuffer> placeResult = Places.GeoDataApi.getPlaceById(googleMapsApiDirector.getGoogleApiClient(), placeId);
                        placeResult.setResultCallback(new ResultCallback<PlaceBuffer>() {
                            @Override
                            public void onResult(PlaceBuffer places) {
                                if (places.getCount() == 1) {
                                    if (listCallbacks != null)
                                        listCallbacks.onAddressListClick(places.get(0).getAddress().toString(),
                                                places.get(0).getLatLng().latitude,
                                                places.get(0).getLatLng().longitude);
                                }
                            }
                        });
                    }
                }
            })
        );

**Comment by d-rahul** [comment]
I also encountered the same issue.

Solution is one line of code: myRecyclerViewReference.getRecycledViewPool().clear();

Use before notifyDataSetChanged and new Adapter() initialization for setAdapter

Get it resolved from https://readyandroid.wordpress.com/java-lang-indexoutofboundsexception-inconsistency-detected-invalid-item-position-android-recyclerview/

Nice blog with Android tricks: https://readyandroid.wordpress.com/
