### ISSUE TITLE
IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.

### ISSUE THREAD

**Issue by Sottti** [umano/AndroidSlidingUpPanel#872]
Crashlytics is blaming the library, but I have no idea what's going on.

This started to happen just after updating to 3.4.0, never happened before on 3.3.1 (but that might be a coincidence).

This is one of the Crashlytics outputs:
```
Fatal Exception: java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
       at android.view.ViewGroup.addViewInner(ViewGroup.java:4310)
       at android.view.ViewGroup.addView(ViewGroup.java:4146)
       at android.view.ViewGroup.addView(ViewGroup.java:4087)
       at android.support.v7.widget.RecyclerView$5.addView(RecyclerView.java:746)
       at android.support.v7.widget.ChildHelper.addView(ChildHelper.java:107)
       at android.support.v7.widget.RecyclerView$LayoutManager.addViewInt(RecyclerView.java:8003)
       at android.support.v7.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:7961)
       at android.support.v7.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:7949)
       at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1570)
       at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1516)
       at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:608)
       at android.support.v7.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:3644)
       at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3408)
       at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3962)
       at android.view.View.layout(View.java:16647)
       at android.view.ViewGroup.layout(ViewGroup.java:5438)
       at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:610)
       at android.view.View.layout(View.java:16647)
       at android.view.ViewGroup.layout(ViewGroup.java:5438)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
       at android.view.View.layout(View.java:16647)
       at android.view.ViewGroup.layout(ViewGroup.java:5438)
       at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1767)
       at android.view.View.layout(View.java:16647)
       at android.view.ViewGroup.layout(ViewGroup.java:5438)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
       at android.view.View.layout(View.java:16647)
       at android.view.ViewGroup.layout(ViewGroup.java:5438)
       at com.sothree.slidinguppanel.SlidingUpPanelLayout.onLayout(SlidingUpPanelLayout.java:863)
       at android.view.View.layout(View.java:16647)
       at android.view.ViewGroup.layout(ViewGroup.java:5438)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
       at android.view.View.layout(View.java:16647)
       at android.view.ViewGroup.layout(ViewGroup.java:5438)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
       at android.view.View.layout(View.java:16647)
       at android.view.ViewGroup.layout(ViewGroup.java:5438)
       at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1172)
       at android.view.View.layout(View.java:16647)
       at android.view.ViewGroup.layout(ViewGroup.java:5438)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
       at android.view.View.layout(View.java:16647)
       at android.view.ViewGroup.layout(ViewGroup.java:5438)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
       at android.view.View.layout(View.java:16647)
       at android.view.ViewGroup.layout(ViewGroup.java:5438)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
       at android.view.View.layout(View.java:16647)
       at android.view.ViewGroup.layout(ViewGroup.java:5438)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
       at android.view.View.layout(View.java:16647)
       at android.view.ViewGroup.layout(ViewGroup.java:5438)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
       at com.android.internal.policy.PhoneWindow$DecorView.onLayout(PhoneWindow.java:2682)
       at android.view.View.layout(View.java:16647)
       at android.view.ViewGroup.layout(ViewGroup.java:5438)
       at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2171)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1931)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6013)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
       at android.view.Choreographer.doCallbacks(Choreographer.java:670)
       at android.view.Choreographer.doFrame(Choreographer.java:606)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
       at android.os.Handler.handleCallback(Handler.java:743)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:171)
       at android.app.ActivityThread.main(ActivityThread.java:5417)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

This is another one:
```
Fatal Exception: java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
       at android.view.ViewGroup.addViewInner(ViewGroup.java:3718)
       at android.view.ViewGroup.addView(ViewGroup.java:3564)
       at android.view.ViewGroup.addView(ViewGroup.java:3509)
       at android.support.v7.widget.RecyclerView$5.addView(RecyclerView.java:746)
       at android.support.v7.widget.ChildHelper.addView(ChildHelper.java:107)
       at android.support.v7.widget.RecyclerView$LayoutManager.addViewInt(RecyclerView.java:8003)
       at android.support.v7.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:7961)
       at android.support.v7.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:7949)
       at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1570)
       at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1516)
       at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:608)
       at android.support.v7.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:3644)
       at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3408)
       at android.support.v7.widget.RecyclerView.consumePendingUpdateOperations(RecyclerView.java:1699)
       at android.support.v7.widget.RecyclerView.scrollByInternal(RecyclerView.java:1744)
       at android.support.v7.widget.RecyclerView.onTouchEvent(RecyclerView.java:2970)
       at android.view.View.dispatchTouchEvent(View.java:7790)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2316)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2013)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2322)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2027)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2322)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2027)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2322)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2027)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2322)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2027)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2322)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2027)
       at com.sothree.slidinguppanel.SlidingUpPanelLayout.dispatchTouchEvent(SlidingUpPanelLayout.java:963)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2322)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2027)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2322)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2027)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2322)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2027)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2322)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2027)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2322)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2027)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2322)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2027)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2322)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2027)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2322)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2027)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2145)
       at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1577)
       at android.app.Activity.dispatchTouchEvent(Activity.java:2515)
       at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:68)
       at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:68)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2093)
       at android.view.View.dispatchPointerEvent(View.java:7981)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4384)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4255)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3801)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3851)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3820)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3927)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3828)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3984)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3801)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3851)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3820)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3828)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3801)
       at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6116)
       at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6096)
       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6050)
       at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6246)
       at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
       at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(InputEventReceiver.java)
       at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:176)
       at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:6208)
       at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:6268)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:788)
       at android.view.Choreographer.doCallbacks(Choreographer.java:591)
       at android.view.Choreographer.doFrame(Choreographer.java:558)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:774)
       at android.os.Handler.handleCallback(Handler.java:808)
       at android.os.Handler.dispatchMessage(Handler.java:103)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:5332)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:831)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:647)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by djdance** [comment]
why closed? how did you solve it?
