### ISSUE TITLE
Fatal Exception: java.lang.StackOverflowError 

### ISSUE THREAD

**Issue by ancazapuc9** [umano/AndroidSlidingUpPanel#965]
Hello,
We are using in our project 
 implementation 'com.sothree.slidinguppanel:library:3.3.1'

and we started to experience lately crashes regarding SlidingPanel -> StackOverflowError
below is the stack trace listed. 

Can you please give us an advice of what we might doing wrong?

**Fatal Exception: java.lang.StackOverflowError
       at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:490)
       at android.widget.ImageView.onDraw(ImageView.java:1019)
       at android.view.View.draw(View.java:14493)
       at android.view.View.getDisplayList(View.java:13390)
       at android.view.View.getDisplayList(View.java:13432)
       at android.view.View.draw(View.java:14210)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
       at android.view.View.draw(View.java:14496)
       at android.widget.FrameLayout.draw(FrameLayout.java:472)
       at android.view.View.getDisplayList(View.java:13390)
       at android.view.View.getDisplayList(View.java:13432)
       at android.view.View.draw(View.java:14210)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
       at android.view.View.getDisplayList(View.java:13385)
       at android.view.View.getDisplayList(View.java:13432)
       at android.view.View.draw(View.java:14210)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
       at android.view.View.draw(View.java:14496)
       at android.widget.FrameLayout.draw(FrameLayout.java:472)
       at android.view.View.getDisplayList(View.java:13390)
       at android.view.View.getDisplayList(View.java:13432)
       at android.view.View.draw(View.java:14210)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
       at android.view.View.draw(View.java:14496)
       at android.widget.FrameLayout.draw(FrameLayout.java:472)
       at android.view.View.getDisplayList(View.java:13390)
       at android.view.View.getDisplayList(View.java:13432)
       at android.view.View.draw(View.java:14210)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
       at android.view.View.draw(View.java:14496)
       at android.view.View.getDisplayList(View.java:13390)
       at android.view.View.getDisplayList(View.java:13432)
       at android.view.View.draw(View.java:14210)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
       at android.view.View.draw(View.java:14496)
       at android.widget.FrameLayout.draw(FrameLayout.java:472)
       at android.view.View.getDisplayList(View.java:13390)
       at android.view.View.getDisplayList(View.java:13432)
       at android.view.View.draw(View.java:14210)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
       at android.view.View.draw(View.java:14496)
       at android.view.View.getDisplayList(View.java:13390)
       at android.view.View.getDisplayList(View.java:13432)
       at android.view.View.draw(View.java:14210)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
       at android.view.View.draw(View.java:14496)
       at android.widget.FrameLayout.draw(FrameLayout.java:472)
       at android.view.View.getDisplayList(View.java:13390)
       at android.view.View.getDisplayList(View.java:13432)
       at android.view.View.draw(View.java:14210)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
       at android.view.View.getDisplayList(View.java:13385)
       at android.view.View.getDisplayList(View.java:13432)
       at android.view.View.draw(View.java:14210)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
       at android.view.View.draw(View.java:14496)
       at android.widget.FrameLayout.draw(FrameLayout.java:472)
       at android.view.View.getDisplayList(View.java:13390)
       at android.view.View.getDisplayList(View.java:13432)
       at android.view.View.draw(View.java:14210)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
       at android.view.View.getDisplayList(View.java:13385)
       at android.view.View.getDisplayList(View.java:13432)
       at android.view.View.draw(View.java:14210)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
       at android.support.v7.widget.RecyclerView.drawChild(RecyclerView.java:4703)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
       at android.view.View.draw(View.java:14496)
       at android.support.v7.widget.RecyclerView.draw(RecyclerView.java:4107)
       at android.view.View.getDisplayList(View.java:13390)
       at android.view.View.getDisplayList(View.java:13432)
       at android.view.View.draw(View.java:14210)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
       at android.view.View.draw(View.java:14496)
       at android.widget.FrameLayout.draw(FrameLayout.java:472)
       at android.view.View.getDisplayList(View.java:13390)
       at android.view.View.getDisplayList(View.java:13432)
       at android.view.View.draw(View.java:14210)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
       at android.view.View.getDisplayList(View.java:13385)
       at android.view.View.getDisplayList(View.java:13432)
       at android.view.View.draw(View.java:14210)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
       at android.support.v7.widget.RecyclerView.drawChild(RecyclerView.java:4703)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
       at android.view.View.draw(View.java:14496)
       at android.support.v7.widget.RecyclerView.draw(RecyclerView.java:4107)
       at android.view.View.getDisplayList(View.java:13390)
       at android.view.View.getDisplayList(View.java:13432)
       at android.view.View.draw(View.java:14210)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
       at android.view.View.draw(View.java:14496)
       at android.widget.FrameLayout.draw(FrameLayout.java:472)
       at android.view.View.getDisplayList(View.java:13390)
       at android.view.View.getDisplayList(View.java:13432)
       at android.view.View.draw(View.java:14210)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
       at android.view.View.getDisplayList(View.java:13385)
       at android.view.View.getDisplayList(View.java:13432)
       at android.view.View.draw(View.java:14210)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
       at android.support.constraint.ConstraintLayout.dispatchDraw(ConstraintLayout.java:1966)
       at android.view.View.getDisplayList(View.java:13385)
       at android.view.View.getDisplayList(View.java:13432)
       at android.view.View.draw(View.java:14210)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
       at android.view.View.draw(View.java:14496)
       at android.widget.FrameLayout.draw(FrameLayout.java:472)
       at android.view.View.getDisplayList(View.java:13390)
       at android.view.View.getDisplayList(View.java:13432)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3077)
       at android.view.View.getDisplayList(View.java:13328)
       at android.view.View.getDisplayList(View.java:13432)
       at android.view.View.draw(View.java:14210)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
       at com.sothree.slidinguppanel.SlidingUpPanelLayout.drawChild(SlidingUpPanelLayout.java:1191)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
       at android.view.View.draw(View.java:14496)
       at com.sothree.slidinguppanel.SlidingUpPanelLayout.draw(SlidingUpPanelLayout.java:1244)
       at android.view.View.getDisplayList(View.java:13390)
       at android.view.View.getDisplayList(View.java:13432)
       at android.view.View.draw(View.java:14210)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
       at android.view.View.getDisplayList(View.java:13385)
       at android.view.View.getDisplayList(View.java:13432)
       at android.view.View.draw(View.java:14210)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
       at android.support.v4.widget.DrawerLayout.drawChild(DrawerLayout.java:1366)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
       at android.view.View.getDisplayList(View.java:13385)
       at android.view.View.getDisplayList(View.java:13432)
       at android.view.View.draw(View.java:14210)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
       at android.view.View.draw(View.java:14496)
       at android.widget.FrameLayout.draw(FrameLayout.java:472)
       at android.view.View.getDisplayList(View.java:13390)
       at android.view.View.getDisplayList(View.java:13432)
       at android.view.View.draw(View.java:14210)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
       at android.view.View.getDisplayList(View.java:13385)
       at android.view.View.getDisplayList(View.java:13432)
       at android.view.View.draw(View.java:14210)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
       at android.support.constraint.ConstraintLayout.dispatchDraw(ConstraintLayout.java:1966)
       at android.view.View.getDisplayList(View.java:13385)
       at android.view.View.getDisplayList(View.java:13432)
       at android.view.View.draw(View.java:14210)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
       at android.support.v4.widget.DrawerLayout.drawChild(DrawerLayout.java:1366)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
       at android.view.View.getDisplayList(View.java:13385)
       at android.view.View.getDisplayList(View.java:13432)
       at android.view.View.draw(View.java:14210)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
       at android.view.View.draw(View.java:14496)
       at android.widget.FrameLayout.draw(FrameLayout.java:472)
       at android.view.View.getDisplayList(View.java:13390)
       at android.view.View.getDisplayList(View.java:13432)
       at android.view.View.draw(View.java:14210)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
       at android.view.View.getDisplayList(View.java:13385)
       at android.view.View.getDisplayList(View.java:13432)
       at android.view.View.draw(View.java:14210)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
       at android.view.View.getDisplayList(View.java:13385)
       at android.view.View.getDisplayList(View.java:13432)
       at android.view.View.draw(View.java:14210)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
       at android.view.View.getDisplayList(View.java:13385)
       at android.view.View.getDisplayList(View.java:13432)
       at android.view.View.draw(View.java:14210)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
       at android.view.View.draw(View.java:14496)
       at android.widget.FrameLayout.draw(FrameLayout.java:472)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2326)
       at android.view.View.getDisplayList(View.java:13390)
       at android.view.View.getDisplayList(View.java:13432)
       at android.view.HardwareRenderer$GlRenderer.buildDisplayList(HardwareRenderer.java:1577)
       at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:1451)
       at android.view.ViewRootImpl.draw(ViewRootImpl.java:2377)
       at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2249)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1879)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:996)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5600)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
       at android.view.Choreographer.doCallbacks(Choreographer.java:574)
       at android.view.Choreographer.doFrame(Choreographer.java:544)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5095)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:602)
       at dalvik.system.NativeStart.main(NativeStart.java)**

**Comment by peter-yeh** [comment]
stackoverflow error means ur function is calling itself repeatedly. 
one of your names is the same as ur return type. I don't think this has anything to do with the slider view. can u provide the codes whr it happened?

**Comment by ancazapuc9** [comment]
Thanks for the quick response.
The problem is that I do not know what code to provide you with, since we only got this stacktrace in our Fabric crashlytics. I don't know what action or what particular code caused this. 

I will try to dig up more of these crashes and then come back to you with more precise details.
