### ISSUE TITLE
Drawable drawable/above_shadow has unresolved theme attributes! Consider using Resources.getDrawable(int, Theme) or Context.getDrawable(int).

### ISSUE THREAD

**Issue by DineshIT** [umano/AndroidSlidingUpPanel#999]
Drawable com.:drawable/above_shadow has unresolved theme attributes! Consider using Resources.getDrawable(int, Theme) or Context.getDrawable(int).
    java.lang.RuntimeException
        at android.content.res.Resources.getDrawable(Resources.java:967)
        at com.sothree.slidinguppanel.SlidingUpPanelLayout.<init>(SlidingUpPanelLayout.java:334)
        at com.sothree.slidinguppanel.SlidingUpPanelLayout.<init>(SlidingUpPanelLayout.java:270)
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:876)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1028)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:983)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1145)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1106)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:692)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:544)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:491)
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:775)
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:197)
        at .common.CommonActivity.onCreate(CommonActivity.java:182)
        at activity.DashBoardActivity.onCreate(DashBoardActivity.java:90)
        at android.app.Activity.performCreate(Activity.java:8591)
        at android.app.Activity.performCreate(Activity.java:8570)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1384)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4150)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4325)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2574)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:226)
        at android.os.Looper.loop(Looper.java:313)
        at android.app.ActivityThread.main(ActivityThread.java:8757)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

I'm upgrading my app to latest target API of 33, and while running I'm facing this error

**Comment by Naguchennai** [comment]
yes same error

**Comment by pankajtirole** [comment]
I am also facing the same error
